[package]
name = "spotify_wrapped"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dotenvy = "0.15.7"
reqwest = "0.13.4" # May not need (look into rspotify a bit more)
rspotify = { version = "0.16.1", features = ["cli"] }
serde = "1.0.228" # May not need (look into rspotify a bit more)
tokio = { version = "1", features = ["full"] }
